os:
    - linux
    - osx

env:
    global:
        - PACKAGE="EvalPrinter"
        - TAG="master"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"


before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/$TAG/sbin/travis.sh

install:
    - sh travis.sh bootstrap

before_script:
    - npm install -g coffee-script

script:
    - sh travis.sh run_tests
